---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "voting-application.fullname" . }}-data-reader
rules:
- apiGroups: [""]
  resources: ["secret"]
  resourceNames: ["{{ .Release.Name }}-mssql-linux-secret"]
  verbs: ["get"]