version: 2.1
jobs:
  validate-yamls:
    docker:
      - image: stefanprodan/hrval:v2.6.0
    steps:
      - checkout
      - run:
          name: Validate releases
          environment:
            IGNORE_VALUES: "false"
            KUBE_VER: "1.16.0"
            HELM_VER: "v3"
          command: |
            hrval releases/ $IGNORE_VALUES $KUBE_VER $HELM_VER

workflows:
  version: 2
  validate:
    jobs:
      - validate-yamls:
          filters:
            branches:
              ignore:
                - gh-pages
